# filepath: /Users/ayumu/git/TODO/todo-app/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - tododb_data:/var/lib/postgresql/data

volumes:
  tododb_data: